# ---------- Site basics ----------
baseURL = "https://qianqianshan.github.io/"
languageCode = "en-us"
title = "Random Steps"
theme = "FixIt"

# NEW: replace deprecated `paginate` with the new block
[pagination]
  pagerSize = 10

# Outputs (HTML + RSS for homepage)
[outputs]
  home = ["HTML", "RSS"]

# ---------- Taxonomies ----------
[taxonomies]
  category = "categories"
  tag = "tags"

# ---------- Theme parameters ----------
[params]
  enableSearch = true
  enableBusuanzi = true
  enableKaTeX = true
  enableMermaid = true
  defaultTheme = "auto"
  since = 2025

  # CHANGED: TOC must be a table, not `toc = true`
  [params.page]
    readingTime = true
    # Per-page TOC config (FixIt expects a map)
    [params.page.toc]
      enable = true

  [params.footer]
    enable = true

# ---------- Markdown / rendering ----------
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

# ---------- Sitemap / robots ----------
enableRobotsTXT = true
