# ---------- Site basics ----------
baseURL = "https://qianqianshan.github.io/"
languageCode = "en-us"
title = "MindOrchard"
theme = "FixIt"
paginate = 10
# If you want RSS at the homepage:
[outputs]
  home = ["HTML", "RSS"]

# ---------- Taxonomies ----------
[taxonomies]
  category = "categories"
  tag = "tags"

# ---------- Theme parameters (FixIt / LoveIt style) ----------
[params]
  # Core features you wanted
  enableSearch = true        # client-side search (Lunr/Fuse handled by theme)
  enableBusuanzi = true      # site & per-post view counters
  enableKaTeX = true         # math formulas
  enableMermaid = true       # diagrams

  # Nice reading extras (optional but useful)
  defaultTheme = "auto"      # auto/light/dark
  since = 2025               # shows site age in footer
  # enablePWA = true         # uncomment if you want PWA later

  # Page-level defaults
  [params.page]
    toc = true               # show per-page table of contents
    readingTime = true
    # displayUpdatedDate = true

  # Footer Busuanzi locations (theme controls exact placement; this keeps it on)
  [params.footer]
    enable = true

# ---------- Markdown / rendering ----------
[markup]
  # Allow raw HTML in Markdown (useful for KaTeX shortcodes, custom blocks)
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  # Nicer code highlighting
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = false

  # Optional: tweak built-in Hugo TOC levels (theme uses its own too)
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3
    ordered = false

# ---------- Sitemap / robots ----------
enableRobotsTXT = true
